INSERT INTO "PRODUCT_OIL" ("BERGAMOTA", "CAPIM_LIMAO", "EUCALIPTO", "HORTELA", "LAVANDA", "LIMAO" ) VALUES (true, false, false, true, false, false);
INSERT INTO "PRODUCT_OIL" ("BERGAMOTA", "CAPIM_LIMAO", "EUCALIPTO", "HORTELA", "LAVANDA", "LIMAO" ) VALUES (false, false, true, false, true, false);
INSERT INTO "PRODUCT_OIL" ("BERGAMOTA", "CAPIM_LIMAO", "EUCALIPTO", "HORTELA", "LAVANDA", "LIMAO" ) VALUES (true, true, false, false, true, false);
INSERT INTO "PRODUCT_OIL" ("BERGAMOTA", "CAPIM_LIMAO", "EUCALIPTO", "HORTELA", "LAVANDA", "LIMAO" ) VALUES (false, true, true, false, true, true);
INSERT INTO "PRODUCT_OIL" ("BERGAMOTA", "CAPIM_LIMAO", "EUCALIPTO", "HORTELA", "LAVANDA", "LIMAO" ) VALUES (false, false, true, false, false, true);
INSERT INTO "PRODUCT_OIL" ("BERGAMOTA", "CAPIM_LIMAO", "EUCALIPTO", "HORTELA", "LAVANDA", "LIMAO" ) VALUES (false, true, false, false, false, false);

INSERT INTO "SERVICE" ("TYPE") VALUES ('Limpeza de pele');
INSERT INTO "SERVICE" ("TYPE") VALUES ('Maquiagem');
INSERT INTO "SERVICE" ("TYPE") VALUES ('Limpeza de pele');
INSERT INTO "SERVICE" ("TYPE") VALUES ('Limpeza de pele');
INSERT INTO "SERVICE" ("TYPE") VALUES ('Aromaterapia');
INSERT INTO "SERVICE" ("TYPE") VALUES ('Maquiagem');

INSERT INTO "REQUEST" ("CLIENT_CEP", "CLIENT_COMPLEMENT", "CLIENT_CPF", "CLIENT_EMAIL", "CLIENT_NAME", "CLIENT_NEIGHBORHOOD", "CLIENT_NUMBER", "CLIENT_PHONE", "CLIENT_STATE", "CLIENT_STREET", "COST", "STATUS", "PRODUCT_OIL_ID", "SERVICE_ID") VALUES ('04474090', 'Casa 2', '406.047.590-45', 'jowens@outlook.com', 'Johnny Owens', 'Jardim Santa Terezinha', 517, '(11) 98780-1953', 'SP', 'Rua das Cambevas', 100, 2, 1, 1);
INSERT INTO "REQUEST" ("CLIENT_CEP", "CLIENT_COMPLEMENT", "CLIENT_CPF", "CLIENT_EMAIL", "CLIENT_NAME", "CLIENT_NEIGHBORHOOD", "CLIENT_NUMBER", "CLIENT_PHONE", "CLIENT_STATE", "CLIENT_STREET", "COST", "STATUS", "PRODUCT_OIL_ID", "SERVICE_ID") VALUES ('08717170', '', '346.236.440-57', 'jvitor12@live.com', 'João Vitor', 'Parque Santana', 361, '(11) 93164-8735', 'SP', 'Travessa Lara', 128, 2, 2, 2);
INSERT INTO "REQUEST" ("CLIENT_CEP", "CLIENT_COMPLEMENT", "CLIENT_CPF", "CLIENT_EMAIL", "CLIENT_NAME", "CLIENT_NEIGHBORHOOD", "CLIENT_NUMBER", "CLIENT_PHONE", "CLIENT_STATE", "CLIENT_STREET", "COST", "STATUS", "PRODUCT_OIL_ID", "SERVICE_ID") VALUES ('14092030', 'Casa 1', '773.293.780-54', 'alves.maria7@gmail.com', 'Maria Alves', 'Jardim Anhanguera', 453, '(11) 94253-8265', 'SP', 'Rua Farid Salim', 256, 1, 3, 3);
INSERT INTO "REQUEST" ("CLIENT_CEP", "CLIENT_COMPLEMENT", "CLIENT_CPF", "CLIENT_EMAIL", "CLIENT_NAME", "CLIENT_NEIGHBORHOOD", "CLIENT_NUMBER", "CLIENT_PHONE", "CLIENT_STATE", "CLIENT_STREET", "COST", "STATUS", "PRODUCT_OIL_ID", "SERVICE_ID") VALUES ('05240005', 'Em frente à Pizzaria', '816.870.640-40', 'gabiap@gmail.com', 'Gabriela', 'Chácara Jaraguá', 2, '(11) 96341-3742', 'SP', 'Rua Rio Jundiaí', 147, 3, 4, 4);
INSERT INTO "REQUEST" ("CLIENT_CEP", "CLIENT_COMPLEMENT", "CLIENT_CPF", "CLIENT_EMAIL", "CLIENT_NAME", "CLIENT_NEIGHBORHOOD", "CLIENT_NUMBER", "CLIENT_PHONE", "CLIENT_STATE", "CLIENT_STREET", "COST", "STATUS", "PRODUCT_OIL_ID", "SERVICE_ID") VALUES ('08586180', '', '558.983.630-17', 'moliveira@gmail.com', 'Murilo Oliveira', 'Parque São Pedro', 859, '(11) 98478-8229', 'SP', 'Rua do Bronze', 142, 1, 5, 5);
INSERT INTO "REQUEST" ("CLIENT_CEP", "CLIENT_COMPLEMENT", "CLIENT_CPF", "CLIENT_EMAIL", "CLIENT_NAME", "CLIENT_NEIGHBORHOOD", "CLIENT_NUMBER", "CLIENT_PHONE", "CLIENT_STATE", "CLIENT_STREET", "COST", "STATUS", "PRODUCT_OIL_ID", "SERVICE_ID") VALUES ('12908520', '', '065.741.940-08', 'souza.vi78@gmail.com', 'Vitor Souza', 'Jardim São Lourenço', 098, '(11) 99322-3524', 'SP', 'Rua Alberto Grasson', 158, 4, 6, 6);